spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID:LeECmGtmibebqZVG80hUoUUl7ZefIr7a}
            client-secret: ${AUTH0_CLIENT_SECRET:pgRctA7QdN4fUe2nAQsK9h-1bmh8DA8qRToGFHXSZ7MVFDY33lbVR6J63Ku7Orxo}
            scope:
              - openid
              - profile
              - email
              - read:users
              - read:user_idp_tokens
            redirect-uri: "https://obscure-waffle-pjrqgrjj4475265xr-8080.app.github.dev/login/oauth2/code/auth0"
        provider:
          auth0:
            issuer-uri: ${AUTH0_ISSUER_URI:https://dev-6a8gx4jqe8ymcodi.us.auth0.com/}
            user-name-attribute: sub

auth0:
  domain: ${AUTH0_DOMAIN:dev-6a8gx4jqe8ymcodi.us.auth0.com}
  clientId: ${AUTH0_CLIENT_ID:LeECmGtmibebqZVG80hUoUUl7ZefIr7a}
  clientSecret: ${AUTH0_CLIENT_SECRET:pgRctA7QdN4fUe2nAQsK9h-1bmh8DA8qRToGFHXSZ7MVFDY33lbVR6J63Ku7Orxo}

server:
  port: 8080
  forward-headers-strategy: native
  use-forward-headers: true
  servlet:
    context-path: /

logging:
  level:
    org.springframework.security: DEBUG